org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

kotlin.code.style=official

# 本机代理（如需走 Clash 拉依赖时取消注释）
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7897
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7897
